# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Neehaarika Velavarthy's Blog
tagline:          'Just trying out stuff'
description:      'Nice to meet you!'
url:              http://neha89r.github.io
baseurl:          /

author:
  name:           'Neha'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/neha89r
